services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    image: med7_fastapi
    ports:
      - "8000:80"
    volumes:
      - ./backend/app:/app

  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    image: med7_streamlit
    ports:
      - "80:8501"
    volumes:
      - ./frontend/app:/app
